# fly.toml app configuration file for scoutmark-ba
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'scoutmark-ba'
primary_region = 'lhr'

[build]

[env]
  ENVIRONMENT = 'production'
  SERVER_ADDR = ':8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
